sudo: required
language: node_js
node_js:
        - '10'

cache:
        directories:
                - node_modules
                - .npm/
                - .cache/

before_script:
        - npm ci

script:
        - npm run test
        - npm run test:cover
        - codecov

after_success:
        - bash <(curl -s https://codecov.io/bash)

before_deploy:
        - npm run build

deploy:
        provider: surge
        project: ./build
        domain: minesweeper.surge.sh
        on: master
