Description:
  Infrastructure management user CloudFormation template.
  
Resources:
  
  MinesweeperSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'Minesweeper user secret'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "minesweeper-user"}'
        GenerateStringKey: password
        IncludeSpace: False
        ExcludeLowercase: False
        ExcludeUppercase: False
        PasswordLength: 15
        ExcludeCharacters: '|;,."<>%`'

  Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: minesweeper
      Path: /
      Policies:
        - PolicyName: String
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "ec2:*"
                  - "cloudformation:*"
                  - "secretmanager:*"
                Resource: "*"
  
  MinesweeperUser:
    Type: AWS::IAM::User
    Properties: 
      Groups:
        - minesweeper
      LoginProfile:
        Password: !Join ['', ['{{resolve:secretsmanager:', !Ref MinesweeperSecret, ':SecretString:password}}' ]]
      UserName: !Join ['', ['{{resolve:secretsmanager:', !Ref MinesweeperSecret, ':SecretString:username}}' ]]

Outputs:
  MinesweeperUser:
    Description: Minesweeper User ARN
    Value: !Ref MinesweeperUser
