---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS cluster'

Parameters:

  Environment:
    Description: Environment name, used as a prefix for resources
    Type: String

  ID:
    Description: Unique identifier.
    Type: String
    Default: 999hadvhgchjesr

Resources:
  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EKS Cluster security group
      GroupName: !Sub "${Environment}-cluster-sec-group-${ID}"
      VpcId:
        Fn::ImportValue: !Sub "${Environment}-VPC"
      Tags:
      - Key: !Sub "kubernetes.io/cluster/${Environment}-cluster-${ID}"
        Value: 'owned'
      - Key: 'Name'
        Value: !Sub "${Environment}-cluster-sec-group-${ID}"

  Cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Sub "${Environment}-cluster-${ID}"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${Environment}-Subnet01-${ID}"
          - Fn::ImportValue: !Sub "${Environment}-Subnet02-${ID}"
          - Fn::ImportValue: !Sub "${Environment}-Subnet03-${ID}"
      RoleArn:
        Fn::ImportValue: !Sub "${Environment}::EksServiceRoleArn"
      Version: 1.19

Outputs:

  ClusterSecurityGroup:
    Description: Control plane security group
    Value: !Ref ClusterSecurityGroup
    Export:
      Name: !Sub "${Environment}-cluster-sec-group-${ID}"
  
  Cluster:
    Description: Cluster name
    Value: !Ref Cluster
    Export:
      Name: !Sub "${Environment}-cluster-${ID}"